/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: test.i */

#define SWIGMODULE mywall
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef int intgo;
typedef unsigned int uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include <wallaby/swallaby.h>

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_mywall_c8e484ea3ef70acf(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


short _wrap_accel_x_mywall_c8e484ea3ef70acf() {
  short result;
  short _swig_go_result;
  
  
  result = (short)accel_x();
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_accel_y_mywall_c8e484ea3ef70acf() {
  short result;
  short _swig_go_result;
  
  
  result = (short)accel_y();
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_accel_z_mywall_c8e484ea3ef70acf() {
  short result;
  short _swig_go_result;
  
  
  result = (short)accel_z();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_accel_calibrate_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)accel_calibrate();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_analog_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)analog(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_analog8_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)analog8(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_analog10_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)analog10(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_analog12_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)analog12(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_analog_et_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)analog_et(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_set_analog_pullup_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  set_analog_pullup(arg1,arg2);
  
}


intgo _wrap_get_analog_pullup_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)get_analog_pullup(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_beep_mywall_c8e484ea3ef70acf() {
  beep();
  
}


intgo _wrap_battery_charging_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)battery_charging();
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_power_level_mywall_c8e484ea3ef70acf() {
  float result;
  float _swig_go_result;
  
  
  result = (float)power_level();
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_power_level_nimh_mywall_c8e484ea3ef70acf() {
  float result;
  float _swig_go_result;
  
  
  result = (float)power_level_nimh();
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_power_level_lipo_mywall_c8e484ea3ef70acf() {
  float result;
  float _swig_go_result;
  
  
  result = (float)power_level_lipo();
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_power_level_life_mywall_c8e484ea3ef70acf() {
  float result;
  float _swig_go_result;
  
  
  result = (float)power_level_life();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_shut_down_in_mywall_c8e484ea3ef70acf(double _swig_go_0) {
  double arg1 ;
  
  arg1 = (double)_swig_go_0; 
  
  shut_down_in(arg1);
  
}


void _wrap_wait_for_light_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  wait_for_light(arg1);
  
}


void _wrap_set_a_button_text_mywall_c8e484ea3ef70acf(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  set_a_button_text((char const *)arg1);
  
  free(arg1); 
}


void _wrap_set_b_button_text_mywall_c8e484ea3ef70acf(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  set_b_button_text((char const *)arg1);
  
  free(arg1); 
}


void _wrap_set_c_button_text_mywall_c8e484ea3ef70acf(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  set_c_button_text((char const *)arg1);
  
  free(arg1); 
}


void _wrap_set_x_button_text_mywall_c8e484ea3ef70acf(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  set_x_button_text((char const *)arg1);
  
  free(arg1); 
}


void _wrap_set_y_button_text_mywall_c8e484ea3ef70acf(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  set_y_button_text((char const *)arg1);
  
  free(arg1); 
}


void _wrap_set_z_button_text_mywall_c8e484ea3ef70acf(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  set_z_button_text((char const *)arg1);
  
  free(arg1); 
}


intgo _wrap_a_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)a_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_b_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)b_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_c_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)c_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_x_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)x_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_y_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)y_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_z_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)z_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_side_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)side_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_black_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)black_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_left_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)left_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_right_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)right_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_a_button_clicked_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)a_button_clicked();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_b_button_clicked_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)b_button_clicked();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_c_button_clicked_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)c_button_clicked();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_x_button_clicked_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)x_button_clicked();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_y_button_clicked_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)y_button_clicked();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_z_button_clicked_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)z_button_clicked();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_side_button_clicked_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)side_button_clicked();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_any_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)any_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_extra_buttons_show_mywall_c8e484ea3ef70acf() {
  extra_buttons_show();
  
}


void _wrap_extra_buttons_hide_mywall_c8e484ea3ef70acf() {
  extra_buttons_hide();
  
}


intgo _wrap_get_extra_buttons_visible_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_extra_buttons_visible();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_set_extra_buttons_visible_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  set_extra_buttons_visible(arg1);
  
}


void _wrap_point2_x_set_mywall_c8e484ea3ef70acf(struct point2 *_swig_go_0, intgo _swig_go_1) {
  struct point2 *arg1 = (struct point2 *) 0 ;
  int arg2 ;
  
  arg1 = *(struct point2 **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->x = arg2;
  
}


intgo _wrap_point2_x_get_mywall_c8e484ea3ef70acf(struct point2 *_swig_go_0) {
  struct point2 *arg1 = (struct point2 *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct point2 **)&_swig_go_0; 
  
  result = (int) ((arg1)->x);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_point2_y_set_mywall_c8e484ea3ef70acf(struct point2 *_swig_go_0, intgo _swig_go_1) {
  struct point2 *arg1 = (struct point2 *) 0 ;
  int arg2 ;
  
  arg1 = *(struct point2 **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->y = arg2;
  
}


intgo _wrap_point2_y_get_mywall_c8e484ea3ef70acf(struct point2 *_swig_go_0) {
  struct point2 *arg1 = (struct point2 *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct point2 **)&_swig_go_0; 
  
  result = (int) ((arg1)->y);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct point2 *_wrap_new_point2_mywall_c8e484ea3ef70acf() {
  struct point2 *result = 0 ;
  struct point2 *_swig_go_result;
  
  
  result = (struct point2 *)calloc(1, sizeof(struct point2));
  *(struct point2 **)&_swig_go_result = (struct point2 *)result; 
  return _swig_go_result;
}


void _wrap_delete_point2_mywall_c8e484ea3ef70acf(struct point2 *_swig_go_0) {
  struct point2 *arg1 = (struct point2 *) 0 ;
  
  arg1 = *(struct point2 **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_point3_x_set_mywall_c8e484ea3ef70acf(struct point3 *_swig_go_0, intgo _swig_go_1) {
  struct point3 *arg1 = (struct point3 *) 0 ;
  int arg2 ;
  
  arg1 = *(struct point3 **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->x = arg2;
  
}


intgo _wrap_point3_x_get_mywall_c8e484ea3ef70acf(struct point3 *_swig_go_0) {
  struct point3 *arg1 = (struct point3 *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct point3 **)&_swig_go_0; 
  
  result = (int) ((arg1)->x);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_point3_y_set_mywall_c8e484ea3ef70acf(struct point3 *_swig_go_0, intgo _swig_go_1) {
  struct point3 *arg1 = (struct point3 *) 0 ;
  int arg2 ;
  
  arg1 = *(struct point3 **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->y = arg2;
  
}


intgo _wrap_point3_y_get_mywall_c8e484ea3ef70acf(struct point3 *_swig_go_0) {
  struct point3 *arg1 = (struct point3 *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct point3 **)&_swig_go_0; 
  
  result = (int) ((arg1)->y);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_point3_z_set_mywall_c8e484ea3ef70acf(struct point3 *_swig_go_0, intgo _swig_go_1) {
  struct point3 *arg1 = (struct point3 *) 0 ;
  int arg2 ;
  
  arg1 = *(struct point3 **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->z = arg2;
  
}


intgo _wrap_point3_z_get_mywall_c8e484ea3ef70acf(struct point3 *_swig_go_0) {
  struct point3 *arg1 = (struct point3 *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct point3 **)&_swig_go_0; 
  
  result = (int) ((arg1)->z);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct point3 *_wrap_new_point3_mywall_c8e484ea3ef70acf() {
  struct point3 *result = 0 ;
  struct point3 *_swig_go_result;
  
  
  result = (struct point3 *)calloc(1, sizeof(struct point3));
  *(struct point3 **)&_swig_go_result = (struct point3 *)result; 
  return _swig_go_result;
}


void _wrap_delete_point3_mywall_c8e484ea3ef70acf(struct point3 *_swig_go_0) {
  struct point3 *arg1 = (struct point3 *) 0 ;
  
  arg1 = *(struct point3 **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_rectangle_ulx_set_mywall_c8e484ea3ef70acf(struct rectangle *_swig_go_0, intgo _swig_go_1) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int arg2 ;
  
  arg1 = *(struct rectangle **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->ulx = arg2;
  
}


intgo _wrap_rectangle_ulx_get_mywall_c8e484ea3ef70acf(struct rectangle *_swig_go_0) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct rectangle **)&_swig_go_0; 
  
  result = (int) ((arg1)->ulx);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_rectangle_uly_set_mywall_c8e484ea3ef70acf(struct rectangle *_swig_go_0, intgo _swig_go_1) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int arg2 ;
  
  arg1 = *(struct rectangle **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->uly = arg2;
  
}


intgo _wrap_rectangle_uly_get_mywall_c8e484ea3ef70acf(struct rectangle *_swig_go_0) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct rectangle **)&_swig_go_0; 
  
  result = (int) ((arg1)->uly);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_rectangle_width_set_mywall_c8e484ea3ef70acf(struct rectangle *_swig_go_0, intgo _swig_go_1) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int arg2 ;
  
  arg1 = *(struct rectangle **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->width = arg2;
  
}


intgo _wrap_rectangle_width_get_mywall_c8e484ea3ef70acf(struct rectangle *_swig_go_0) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct rectangle **)&_swig_go_0; 
  
  result = (int) ((arg1)->width);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_rectangle_height_set_mywall_c8e484ea3ef70acf(struct rectangle *_swig_go_0, intgo _swig_go_1) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int arg2 ;
  
  arg1 = *(struct rectangle **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->height = arg2;
  
}


intgo _wrap_rectangle_height_get_mywall_c8e484ea3ef70acf(struct rectangle *_swig_go_0) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct rectangle **)&_swig_go_0; 
  
  result = (int) ((arg1)->height);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct rectangle *_wrap_new_rectangle_mywall_c8e484ea3ef70acf() {
  struct rectangle *result = 0 ;
  struct rectangle *_swig_go_result;
  
  
  result = (struct rectangle *)calloc(1, sizeof(struct rectangle));
  *(struct rectangle **)&_swig_go_result = (struct rectangle *)result; 
  return _swig_go_result;
}


void _wrap_delete_rectangle_mywall_c8e484ea3ef70acf(struct rectangle *_swig_go_0) {
  struct rectangle *arg1 = (struct rectangle *) 0 ;
  
  arg1 = *(struct rectangle **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


struct point2 *_wrap_create_point2_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  point2 result;
  struct point2 *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = create_point2(arg1,arg2);
  {
    point2 * resultptr = (point2 *)malloc(sizeof(point2));
    memmove(resultptr, &result, sizeof(point2));
    *(point2 **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct point3 *_wrap_create_point3_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  point3 result;
  struct point3 *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = create_point3(arg1,arg2,arg3);
  {
    point3 * resultptr = (point3 *)malloc(sizeof(point3));
    memmove(resultptr, &result, sizeof(point3));
    *(point3 **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct rectangle *_wrap_create_rectangle_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  rectangle result;
  struct rectangle *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  
  result = create_rectangle(arg1,arg2,arg3,arg4);
  {
    rectangle * resultptr = (rectangle *)malloc(sizeof(rectangle));
    memmove(resultptr, &result, sizeof(rectangle));
    *(rectangle **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_pixel_r_set_mywall_c8e484ea3ef70acf(struct pixel *_swig_go_0, intgo _swig_go_1) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  int arg2 ;
  
  arg1 = *(struct pixel **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->r = arg2;
  
}


intgo _wrap_pixel_r_get_mywall_c8e484ea3ef70acf(struct pixel *_swig_go_0) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct pixel **)&_swig_go_0; 
  
  result = (int) ((arg1)->r);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_pixel_g_set_mywall_c8e484ea3ef70acf(struct pixel *_swig_go_0, intgo _swig_go_1) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  int arg2 ;
  
  arg1 = *(struct pixel **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->g = arg2;
  
}


intgo _wrap_pixel_g_get_mywall_c8e484ea3ef70acf(struct pixel *_swig_go_0) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct pixel **)&_swig_go_0; 
  
  result = (int) ((arg1)->g);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_pixel_b_set_mywall_c8e484ea3ef70acf(struct pixel *_swig_go_0, intgo _swig_go_1) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  int arg2 ;
  
  arg1 = *(struct pixel **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->b = arg2;
  
}


intgo _wrap_pixel_b_get_mywall_c8e484ea3ef70acf(struct pixel *_swig_go_0) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct pixel **)&_swig_go_0; 
  
  result = (int) ((arg1)->b);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct pixel *_wrap_new_pixel_mywall_c8e484ea3ef70acf() {
  struct pixel *result = 0 ;
  struct pixel *_swig_go_result;
  
  
  result = (struct pixel *)calloc(1, sizeof(struct pixel));
  *(struct pixel **)&_swig_go_result = (struct pixel *)result; 
  return _swig_go_result;
}


void _wrap_delete_pixel_mywall_c8e484ea3ef70acf(struct pixel *_swig_go_0) {
  struct pixel *arg1 = (struct pixel *) 0 ;
  
  arg1 = *(struct pixel **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


intgo _wrap_LOW_RES_mywall_c8e484ea3ef70acf() {
  enum Resolution result;
  intgo _swig_go_result;
  
  
  result = LOW_RES;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MED_RES_mywall_c8e484ea3ef70acf() {
  enum Resolution result;
  intgo _swig_go_result;
  
  
  result = MED_RES;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_HIGH_RES_mywall_c8e484ea3ef70acf() {
  enum Resolution result;
  intgo _swig_go_result;
  
  
  result = HIGH_RES;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_NATIVE_RES_mywall_c8e484ea3ef70acf() {
  enum Resolution result;
  intgo _swig_go_result;
  
  
  result = NATIVE_RES;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_WHITE_2016_mywall_c8e484ea3ef70acf() {
  enum Model result;
  intgo _swig_go_result;
  
  
  result = WHITE_2016;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_BLACK_2017_mywall_c8e484ea3ef70acf() {
  enum Model result;
  intgo _swig_go_result;
  
  
  result = BLACK_2017;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_camera_open_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)camera_open();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_camera_open_black_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)camera_open_black();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_camera_open_at_res_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  enum Resolution arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (enum Resolution)_swig_go_0; 
  
  result = (int)camera_open_at_res(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_camera_open_device_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  enum Resolution arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (enum Resolution)_swig_go_1; 
  
  result = (int)camera_open_device(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_camera_open_device_model_at_res_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  enum Model arg2 ;
  enum Resolution arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (enum Model)_swig_go_1; 
  arg3 = (enum Resolution)_swig_go_2; 
  
  result = (int)camera_open_device_model_at_res(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_camera_load_config_mywall_c8e484ea3ef70acf(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (int)camera_load_config((char const *)arg1);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


void _wrap_set_camera_width_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  set_camera_width(arg1);
  
}


void _wrap_set_camera_height_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  set_camera_height(arg1);
  
}


intgo _wrap_get_camera_width_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_camera_width();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_camera_height_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_camera_height();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_camera_update_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)camera_update();
  _swig_go_result = result; 
  return _swig_go_result;
}


struct pixel *_wrap_get_camera_pixel_mywall_c8e484ea3ef70acf(struct point2 *_swig_go_0) {
  point2 arg1 ;
  point2 *argp1 ;
  pixel result;
  struct pixel *_swig_go_result;
  
  
  argp1 = (point2 *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null point2");
  }
  arg1 = (point2)*argp1;
  
  
  result = get_camera_pixel(arg1);
  {
    pixel * resultptr = (pixel *)malloc(sizeof(pixel));
    memmove(resultptr, &result, sizeof(pixel));
    *(pixel **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


intgo _wrap_get_channel_count_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_channel_count();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_count_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)get_object_count(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_get_object_data_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (char *)get_object_data(arg1,arg2);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_get_code_num_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_code_num(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_data_length_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_data_length(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_get_object_confidence_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  double result;
  double _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (double)get_object_confidence(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_area_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_area(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct rectangle *_wrap_get_object_bbox_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  rectangle result;
  struct rectangle *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = get_object_bbox(arg1,arg2);
  {
    rectangle * resultptr = (rectangle *)malloc(sizeof(rectangle));
    memmove(resultptr, &result, sizeof(rectangle));
    *(rectangle **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


intgo _wrap_get_object_bbox_ulx_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_bbox_ulx(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_bbox_uly_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_bbox_uly(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_bbox_brx_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_bbox_brx(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_bbox_bry_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_bbox_bry(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_bbox_width_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_bbox_width(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_bbox_height_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_bbox_height(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct point2 *_wrap_get_object_centroid_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  point2 result;
  struct point2 *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = get_object_centroid(arg1,arg2);
  {
    point2 * resultptr = (point2 *)malloc(sizeof(point2));
    memmove(resultptr, &result, sizeof(point2));
    *(point2 **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


intgo _wrap_get_object_centroid_column_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_centroid_column(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_centroid_x_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_centroid_x(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_centroid_row_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_centroid_row(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_centroid_y_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_centroid_y(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct point2 *_wrap_get_object_center_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  point2 result;
  struct point2 *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = get_object_center(arg1,arg2);
  {
    point2 * resultptr = (point2 *)malloc(sizeof(point2));
    memmove(resultptr, &result, sizeof(point2));
    *(point2 **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


intgo _wrap_get_object_center_column_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_center_column(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_center_x_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_center_x(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_center_row_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_center_row(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_object_center_y_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)get_object_center_y(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_camera_close_mywall_c8e484ea3ef70acf() {
  camera_close();
  
}


void _wrap_set_camera_config_base_path_mywall_c8e484ea3ef70acf(_gostring_ _swig_go_0) {
  char *arg1 = (char *) (char *)0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  set_camera_config_base_path((char const *)arg1);
  
  free(arg1); 
}


char *_wrap_get_camera_frame_row_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  unsigned int arg1 ;
  unsigned char *result = 0 ;
  char *_swig_go_result;
  
  arg1 = (unsigned int)_swig_go_0; 
  
  result = (unsigned char *)get_camera_frame_row(arg1);
  *(unsigned char **)&_swig_go_result = (unsigned char *)result; 
  return _swig_go_result;
}


char *_wrap_get_camera_frame_mywall_c8e484ea3ef70acf() {
  unsigned char *result = 0 ;
  char *_swig_go_result;
  
  
  result = (unsigned char *)get_camera_frame();
  *(unsigned char **)&_swig_go_result = (unsigned char *)result; 
  return _swig_go_result;
}


intgo _wrap_get_camera_element_size_mywall_c8e484ea3ef70acf() {
  unsigned int result;
  intgo _swig_go_result;
  
  
  result = (unsigned int)get_camera_element_size();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_calibrate_compass_mywall_c8e484ea3ef70acf() {
  calibrate_compass();
  
}


void _wrap_set_compass_params_mywall_c8e484ea3ef70acf(float _swig_go_0, float _swig_go_1, float _swig_go_2, float _swig_go_3, float _swig_go_4, float _swig_go_5, float _swig_go_6) {
  float arg1 ;
  float arg2 ;
  float arg3 ;
  float arg4 ;
  float arg5 ;
  float arg6 ;
  float arg7 ;
  
  arg1 = (float)_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  arg5 = (float)_swig_go_4; 
  arg6 = (float)_swig_go_5; 
  arg7 = (float)_swig_go_6; 
  
  set_compass_params(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  
}


float _wrap_get_compass_angle_mywall_c8e484ea3ef70acf() {
  float result;
  float _swig_go_result;
  
  
  result = (float)get_compass_angle();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_console_clear_mywall_c8e484ea3ef70acf() {
  console_clear();
  
}


intgo _wrap_create_connect_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)create_connect();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_create_connect_once_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)create_connect_once();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_create_disconnect_mywall_c8e484ea3ef70acf() {
  create_disconnect();
  
}


void _wrap_create_start_mywall_c8e484ea3ef70acf() {
  create_start();
  
}


void _wrap_create_passive_mywall_c8e484ea3ef70acf() {
  create_passive();
  
}


void _wrap_create_safe_mywall_c8e484ea3ef70acf() {
  create_safe();
  
}


void _wrap_create_full_mywall_c8e484ea3ef70acf() {
  create_full();
  
}


void _wrap_create_spot_mywall_c8e484ea3ef70acf() {
  create_spot();
  
}


void _wrap_create_cover_mywall_c8e484ea3ef70acf() {
  create_cover();
  
}


void _wrap_create_demo_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  create_demo(arg1);
  
}


void _wrap_create_cover_dock_mywall_c8e484ea3ef70acf() {
  create_cover_dock();
  
}


intgo _wrap_get_create_mode_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_mode();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_lbump_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_lbump();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rbump_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rbump();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_lwdrop_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_lwdrop();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_cwdrop_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_cwdrop();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rwdrop_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rwdrop();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_wall_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_wall();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_lcliff_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_lcliff();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_lfcliff_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_lfcliff();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rfcliff_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rfcliff();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rcliff_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rcliff();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_llightbump_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_llightbump();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_lflightbump_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_lflightbump();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_lclightbump_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_lclightbump();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rclightbump_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rclightbump();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rflightbump_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rflightbump();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rlightbump_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rlightbump();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_llightbump_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_llightbump_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rlightbump_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rlightbump_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_lflightbump_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_lflightbump_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_lclightbump_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_lclightbump_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rclightbump_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rclightbump_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rflightbump_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rflightbump_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_vwall_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_vwall();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_overcurrents_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_overcurrents();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_infrared_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_infrared();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_advance_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_advance_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_play_button_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_play_button();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_normalized_angle_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_normalized_angle();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_set_create_normalized_angle_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  set_create_normalized_angle(arg1);
  
}


intgo _wrap_get_create_total_angle_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_total_angle();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_set_create_total_angle_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  set_create_total_angle(arg1);
  
}


intgo _wrap_get_create_distance_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_distance();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_set_create_distance_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  set_create_distance(arg1);
  
}


intgo _wrap_get_create_battery_charging_state_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_battery_charging_state();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_battery_voltage_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_battery_voltage();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_battery_current_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_battery_current();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_battery_temp_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_battery_temp();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_battery_charge_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_battery_charge();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_battery_capacity_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_battery_capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_wall_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_wall_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_lcliff_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_lcliff_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_lfcliff_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_lfcliff_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rfcliff_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rfcliff_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_rcliff_amt_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_rcliff_amt();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_bay_DI_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_bay_DI();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_bay_AI_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_bay_AI();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_song_number_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_song_number();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_song_playing_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_song_playing();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_number_of_stream_packets_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_number_of_stream_packets();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_requested_velocity_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_requested_velocity();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_requested_radius_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_requested_radius();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_requested_right_velocity_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_requested_right_velocity();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_create_requested_left_velocity_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)get_create_requested_left_velocity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_create_stop_mywall_c8e484ea3ef70acf() {
  create_stop();
  
}


void _wrap_create_drive_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  create_drive(arg1,arg2);
  
}


void _wrap_create_drive_straight_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  create_drive_straight(arg1);
  
}


void _wrap_create_spin_CW_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  create_spin_CW(arg1);
  
}


void _wrap_create_spin_CCW_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  create_spin_CCW(arg1);
  
}


void _wrap_create_drive_direct_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  create_drive_direct(arg1,arg2);
  
}


void _wrap_create_spin_block_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  create_spin_block(arg1,arg2);
  
}


intgo _wrap__create_get_raw_encoders_mywall_c8e484ea3ef70acf(long long *_swig_go_0, long long *_swig_go_1) {
  long *arg1 = (long *) 0 ;
  long *arg2 = (long *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(long **)&_swig_go_0; 
  arg2 = *(long **)&_swig_go_1; 
  
  result = (int)_create_get_raw_encoders(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_create_advance_led_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  create_advance_led(arg1);
  
}


void _wrap_create_play_led_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  create_play_led(arg1);
  
}


void _wrap_create_power_led_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  create_power_led(arg1,arg2);
  
}


void _wrap_create_digital_output_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  create_digital_output(arg1);
  
}


void _wrap_create_pwm_low_side_drivers_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  create_pwm_low_side_drivers(arg1,arg2,arg3);
  
}


void _wrap_create_low_side_drivers_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  create_low_side_drivers(arg1,arg2,arg3);
  
}


void _wrap_create_load_song_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  create_load_song(arg1);
  
}


void _wrap_create_play_song_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  create_play_song(arg1);
  
}


intgo _wrap_create_read_block_mywall_c8e484ea3ef70acf(_gostring_ _swig_go_0, intgo _swig_go_1) {
  char *arg1 = (char *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = (int)_swig_go_1; 
  
  result = (int)create_read_block(arg1,arg2);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


void _wrap_create_write_byte_mywall_c8e484ea3ef70acf(char _swig_go_0) {
  char arg1 ;
  
  arg1 = (char)_swig_go_0; 
  
  create_write_byte(arg1);
  
}


void _wrap_create_clear_serial_buffer_mywall_c8e484ea3ef70acf() {
  create_clear_serial_buffer();
  
}


intgo _wrap_Baud57600_mywall_c8e484ea3ef70acf() {
  enum BaudRate result;
  intgo _swig_go_result;
  
  
  result = Baud57600;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Baud115200_mywall_c8e484ea3ef70acf() {
  enum BaudRate result;
  intgo _swig_go_result;
  
  
  result = Baud115200;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_get_create_baud_rate_mywall_c8e484ea3ef70acf() {
  enum BaudRate result;
  intgo _swig_go_result;
  
  
  result = (enum BaudRate)get_create_baud_rate();
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_set_create_baud_rate_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  enum BaudRate arg1 ;
  
  arg1 = (enum BaudRate)_swig_go_0; 
  
  set_create_baud_rate(arg1);
  
}


intgo _wrap_digital_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)digital(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_set_digital_value_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  set_digital_value(arg1,arg2);
  
}


intgo _wrap_get_digital_value_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)get_digital_value(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_set_digital_output_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  set_digital_output(arg1,arg2);
  
}


intgo _wrap_get_digital_output_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)get_digital_output(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_digital_pullup_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)get_digital_pullup(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_set_digital_pullup_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  set_digital_pullup(arg1,arg2);
  
}


void _wrap_display_clear_mywall_c8e484ea3ef70acf() {
  display_clear();
  
}


void _wrap_display_printf_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  int arg1 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  void *arg4 = 0 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  display_printf(arg1,arg2,(char const *)arg3,arg4);
  
  free(arg3); 
}


void _wrap_set_auto_publish_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  set_auto_publish(arg1);
  
}


void _wrap_publish_mywall_c8e484ea3ef70acf() {
  publish();
  
}


void _wrap_halt_mywall_c8e484ea3ef70acf() {
  halt();
  
}


void _wrap_freeze_halt_mywall_c8e484ea3ef70acf() {
  freeze_halt();
  
}


short _wrap_gyro_x_mywall_c8e484ea3ef70acf() {
  short result;
  short _swig_go_result;
  
  
  result = (short)gyro_x();
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_gyro_y_mywall_c8e484ea3ef70acf() {
  short result;
  short _swig_go_result;
  
  
  result = (short)gyro_y();
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_gyro_z_mywall_c8e484ea3ef70acf() {
  short result;
  short _swig_go_result;
  
  
  result = (short)gyro_z();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_gyro_calibrate_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)gyro_calibrate();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ir_read_mywall_c8e484ea3ef70acf() {
  ir_read();
  
}


void _wrap_ir_write_mywall_c8e484ea3ef70acf() {
  ir_write();
  
}


short _wrap_magneto_x_mywall_c8e484ea3ef70acf() {
  short result;
  short _swig_go_result;
  
  
  result = (short)magneto_x();
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_magneto_y_mywall_c8e484ea3ef70acf() {
  short result;
  short _swig_go_result;
  
  
  result = (short)magneto_y();
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_magneto_z_mywall_c8e484ea3ef70acf() {
  short result;
  short _swig_go_result;
  
  
  result = (short)magneto_z();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_magneto_calibrate_mywall_c8e484ea3ef70acf() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)magneto_calibrate();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_motor_position_counter_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)get_motor_position_counter(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_gmpc_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)gmpc(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_clear_motor_position_counter_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  clear_motor_position_counter(arg1);
  
}


void _wrap_cmpc_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  cmpc(arg1);
  
}


intgo _wrap_move_at_velocity_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)move_at_velocity(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_mav_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)mav(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_move_to_position_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)move_to_position(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_mtp_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)mtp(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_move_relative_position_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)move_relative_position(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_mrp_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)mrp(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_set_pid_gains_mywall_c8e484ea3ef70acf(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, short _swig_go_3, short _swig_go_4, short _swig_go_5, short _swig_go_6) {
  int arg1 ;
  short arg2 ;
  short arg3 ;
  short arg4 ;
  short arg5 ;
  short arg6 ;
  short arg7 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (short)_swig_go_1; 
  arg3 = (short)_swig_go_2; 
  arg4 = (short)_swig_go_3; 
  arg5 = (short)_swig_go_4; 
  arg6 = (short)_swig_go_5; 
  arg7 = (short)_swig_go_6; 
  
  set_pid_gains(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  
}


void _wrap_get_pid_gains_mywall_c8e484ea3ef70acf(intgo _swig_go_0, short *_swig_go_1, short *_swig_go_2, short *_swig_go_3, short *_swig_go_4, short *_swig_go_5, short *_swig_go_6) {
  int arg1 ;
  short *arg2 = (short *) 0 ;
  short *arg3 = (short *) 0 ;
  short *arg4 = (short *) 0 ;
  short *arg5 = (short *) 0 ;
  short *arg6 = (short *) 0 ;
  short *arg7 = (short *) 0 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = *(short **)&_swig_go_1; 
  arg3 = *(short **)&_swig_go_2; 
  arg4 = *(short **)&_swig_go_3; 
  arg5 = *(short **)&_swig_go_4; 
  arg6 = *(short **)&_swig_go_5; 
  arg7 = *(short **)&_swig_go_6; 
  
  get_pid_gains(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  
}


intgo _wrap_freeze_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)freeze(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_motor_done_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)get_motor_done(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_block_motor_done_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  block_motor_done(arg1);
  
}


void _wrap_bmd_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  bmd(arg1);
  
}


intgo _wrap_setpwm_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)setpwm(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_getpwm_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)getpwm(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_fd_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  fd(arg1);
  
}


void _wrap_bk_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  bk(arg1);
  
}


void _wrap_motor_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  motor(arg1,arg2);
  
}


void _wrap_motor_power_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  motor_power(arg1,arg2);
  
}


void _wrap_off_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  off(arg1);
  
}


void _wrap_alloff_mywall_c8e484ea3ef70acf() {
  alloff();
  
}


void _wrap_ao_mywall_c8e484ea3ef70acf() {
  ao();
  
}


long long _wrap_get_robot_states_sequence_num_mywall_c8e484ea3ef70acf() {
  unsigned long result;
  long long _swig_go_result;
  
  
  result = (unsigned long)get_robot_states_sequence_num();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_get_robot_update_count_mywall_c8e484ea3ef70acf() {
  unsigned long result;
  long long _swig_go_result;
  
  
  result = (unsigned long)get_robot_update_count();
  _swig_go_result = result; 
  return _swig_go_result;
}


short _wrap_get_robot_firmware_version_mywall_c8e484ea3ef70acf() {
  unsigned short result;
  short _swig_go_result;
  
  
  result = (unsigned short)get_robot_firmware_version();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_set_robot_update_delay_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  unsigned int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (unsigned int)_swig_go_0; 
  
  result = (int)set_robot_update_delay(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_robot_update_delay_mywall_c8e484ea3ef70acf() {
  unsigned int result;
  intgo _swig_go_result;
  
  
  result = (unsigned int)get_robot_update_delay();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_set_low_volt_threshold_mywall_c8e484ea3ef70acf(float _swig_go_0) {
  float arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (float)_swig_go_0; 
  
  result = (int)set_low_volt_threshold(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_get_low_volt_threshold_mywall_c8e484ea3ef70acf() {
  float result;
  float _swig_go_result;
  
  
  result = (float)get_low_volt_threshold();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_enable_servo_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  enable_servo(arg1);
  
}


void _wrap_disable_servo_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  disable_servo(arg1);
  
}


void _wrap_enable_servos_mywall_c8e484ea3ef70acf() {
  enable_servos();
  
}


void _wrap_disable_servos_mywall_c8e484ea3ef70acf() {
  disable_servos();
  
}


void _wrap_set_servo_enabled_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  set_servo_enabled(arg1,arg2);
  
}


intgo _wrap_get_servo_enabled_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)get_servo_enabled(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_get_servo_position_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)get_servo_position(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_set_servo_position_mywall_c8e484ea3ef70acf(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  set_servo_position(arg1,arg2);
  
}


void _wrap_mutex_data_set_mywall_c8e484ea3ef70acf(mutex *_swig_go_0, void *_swig_go_1) {
  mutex *arg1 = (mutex *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = *(mutex **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  if (arg1) (arg1)->data = arg2;
  
}


void *_wrap_mutex_data_get_mywall_c8e484ea3ef70acf(mutex *_swig_go_0) {
  mutex *arg1 = (mutex *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(mutex **)&_swig_go_0; 
  
  result = (void *) ((arg1)->data);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


mutex *_wrap_new_mutex_mywall_c8e484ea3ef70acf() {
  mutex *result = 0 ;
  mutex *_swig_go_result;
  
  
  result = (mutex *)calloc(1, sizeof(mutex));
  *(mutex **)&_swig_go_result = (mutex *)result; 
  return _swig_go_result;
}


void _wrap_delete_mutex_mywall_c8e484ea3ef70acf(mutex *_swig_go_0) {
  mutex *arg1 = (mutex *) 0 ;
  
  arg1 = *(mutex **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_thread_data_set_mywall_c8e484ea3ef70acf(thread *_swig_go_0, void *_swig_go_1) {
  thread *arg1 = (thread *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = *(thread **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  if (arg1) (arg1)->data = arg2;
  
}


void *_wrap_thread_data_get_mywall_c8e484ea3ef70acf(thread *_swig_go_0) {
  thread *arg1 = (thread *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(thread **)&_swig_go_0; 
  
  result = (void *) ((arg1)->data);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


thread *_wrap_new_thread_mywall_c8e484ea3ef70acf() {
  thread *result = 0 ;
  thread *_swig_go_result;
  
  
  result = (thread *)calloc(1, sizeof(thread));
  *(thread **)&_swig_go_result = (thread *)result; 
  return _swig_go_result;
}


void _wrap_delete_thread_mywall_c8e484ea3ef70acf(thread *_swig_go_0) {
  thread *arg1 = (thread *) 0 ;
  
  arg1 = *(thread **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


mutex *_wrap_mutex_create_mywall_c8e484ea3ef70acf() {
  mutex result;
  mutex *_swig_go_result;
  
  
  result = mutex_create();
  {
    mutex * resultptr = (mutex *)malloc(sizeof(mutex));
    memmove(resultptr, &result, sizeof(mutex));
    *(mutex **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_mutex_lock_mywall_c8e484ea3ef70acf(mutex *_swig_go_0) {
  mutex arg1 ;
  mutex *argp1 ;
  
  
  argp1 = (mutex *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null mutex");
  }
  arg1 = (mutex)*argp1;
  
  
  mutex_lock(arg1);
  
}


intgo _wrap_mutex_trylock_mywall_c8e484ea3ef70acf(mutex *_swig_go_0) {
  mutex arg1 ;
  mutex *argp1 ;
  int result;
  intgo _swig_go_result;
  
  
  argp1 = (mutex *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null mutex");
  }
  arg1 = (mutex)*argp1;
  
  
  result = (int)mutex_trylock(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_mutex_unlock_mywall_c8e484ea3ef70acf(mutex *_swig_go_0) {
  mutex arg1 ;
  mutex *argp1 ;
  
  
  argp1 = (mutex *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null mutex");
  }
  arg1 = (mutex)*argp1;
  
  
  mutex_unlock(arg1);
  
}


void _wrap_mutex_destroy_mywall_c8e484ea3ef70acf(mutex *_swig_go_0) {
  mutex arg1 ;
  mutex *argp1 ;
  
  
  argp1 = (mutex *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null mutex");
  }
  arg1 = (mutex)*argp1;
  
  
  mutex_destroy(arg1);
  
}


thread *_wrap_thread_create_mywall_c8e484ea3ef70acf(void** _swig_go_0) {
  thread_function arg1 = (thread_function) 0 ;
  thread result;
  thread *_swig_go_result;
  
  arg1 = *(thread_function *)&_swig_go_0; 
  
  result = thread_create(arg1);
  {
    thread * resultptr = (thread *)malloc(sizeof(thread));
    memmove(resultptr, &result, sizeof(thread));
    *(thread **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_thread_start_mywall_c8e484ea3ef70acf(thread *_swig_go_0) {
  thread arg1 ;
  thread *argp1 ;
  
  
  argp1 = (thread *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null thread");
  }
  arg1 = (thread)*argp1;
  
  
  thread_start(arg1);
  
}


void _wrap_thread_wait_mywall_c8e484ea3ef70acf(thread *_swig_go_0) {
  thread arg1 ;
  thread *argp1 ;
  
  
  argp1 = (thread *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null thread");
  }
  arg1 = (thread)*argp1;
  
  
  thread_wait(arg1);
  
}


void _wrap_thread_destroy_mywall_c8e484ea3ef70acf(thread *_swig_go_0) {
  thread arg1 ;
  thread *argp1 ;
  
  
  argp1 = (thread *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null thread");
  }
  arg1 = (thread)*argp1;
  
  
  thread_destroy(arg1);
  
}


void _wrap_msleep_mywall_c8e484ea3ef70acf(long long _swig_go_0) {
  long arg1 ;
  
  arg1 = (long)_swig_go_0; 
  
  msleep(arg1);
  
}


long long _wrap_systime_mywall_c8e484ea3ef70acf() {
  unsigned long result;
  long long _swig_go_result;
  
  
  result = (unsigned long)systime();
  _swig_go_result = result; 
  return _swig_go_result;
}


double _wrap_seconds_mywall_c8e484ea3ef70acf() {
  double result;
  double _swig_go_result;
  
  
  result = (double)seconds();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_wait_for_milliseconds_mywall_c8e484ea3ef70acf(long long _swig_go_0) {
  long arg1 ;
  
  arg1 = (long)_swig_go_0; 
  
  wait_for_milliseconds(arg1);
  
}


void _wrap_wait_for_touch_mywall_c8e484ea3ef70acf(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  wait_for_touch(arg1);
  
}


void _wrap_wait_for_a_button_mywall_c8e484ea3ef70acf() {
  wait_for_a_button();
  
}


void _wrap_wait_for_b_button_mywall_c8e484ea3ef70acf() {
  wait_for_b_button();
  
}


void _wrap_wait_for_c_button_mywall_c8e484ea3ef70acf() {
  wait_for_c_button();
  
}


void _wrap_wait_for_x_button_mywall_c8e484ea3ef70acf() {
  wait_for_x_button();
  
}


void _wrap_wait_for_y_button_mywall_c8e484ea3ef70acf() {
  wait_for_y_button();
  
}


void _wrap_wait_for_z_button_mywall_c8e484ea3ef70acf() {
  wait_for_z_button();
  
}


void _wrap_wait_for_side_button_mywall_c8e484ea3ef70acf() {
  wait_for_side_button();
  
}


void _wrap_wait_for_any_button_mywall_c8e484ea3ef70acf() {
  wait_for_any_button();
  
}


void _wrap_wait_for_a_button_clicked_mywall_c8e484ea3ef70acf() {
  wait_for_a_button_clicked();
  
}


void _wrap_wait_for_b_button_clicked_mywall_c8e484ea3ef70acf() {
  wait_for_b_button_clicked();
  
}


void _wrap_wait_for_c_button_clicked_mywall_c8e484ea3ef70acf() {
  wait_for_c_button_clicked();
  
}


void _wrap_wait_for_x_button_clicked_mywall_c8e484ea3ef70acf() {
  wait_for_x_button_clicked();
  
}


void _wrap_wait_for_y_button_clicked_mywall_c8e484ea3ef70acf() {
  wait_for_y_button_clicked();
  
}


void _wrap_wait_for_z_button_clicked_mywall_c8e484ea3ef70acf() {
  wait_for_z_button_clicked();
  
}


void _wrap_wait_for_side_button_clicked_mywall_c8e484ea3ef70acf() {
  wait_for_side_button_clicked();
  
}


#ifdef __cplusplus
}
#endif

