/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: wallaby.i

package wallaby

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef int intgo;
typedef unsigned int uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#cgo LDFLAGS: -L/usr/lib -l wallaby 

typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
extern void _wrap_Swig_free_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern short _wrap_accel_x_wallaby_78ff119e04ce6c7b(void);
extern short _wrap_accel_y_wallaby_78ff119e04ce6c7b(void);
extern short _wrap_accel_z_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_accel_calibrate_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_analog_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_analog8_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_analog10_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_analog12_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_analog_et_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_set_analog_pullup_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_analog_pullup_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_beep_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_battery_charging_wallaby_78ff119e04ce6c7b(void);
extern float _wrap_power_level_wallaby_78ff119e04ce6c7b(void);
extern float _wrap_power_level_nimh_wallaby_78ff119e04ce6c7b(void);
extern float _wrap_power_level_lipo_wallaby_78ff119e04ce6c7b(void);
extern float _wrap_power_level_life_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_shut_down_in_wallaby_78ff119e04ce6c7b(double arg1);
extern void _wrap_wait_for_light_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_set_a_button_text_wallaby_78ff119e04ce6c7b(swig_type_1 arg1);
extern void _wrap_set_b_button_text_wallaby_78ff119e04ce6c7b(swig_type_2 arg1);
extern void _wrap_set_c_button_text_wallaby_78ff119e04ce6c7b(swig_type_3 arg1);
extern void _wrap_set_x_button_text_wallaby_78ff119e04ce6c7b(swig_type_4 arg1);
extern void _wrap_set_y_button_text_wallaby_78ff119e04ce6c7b(swig_type_5 arg1);
extern void _wrap_set_z_button_text_wallaby_78ff119e04ce6c7b(swig_type_6 arg1);
extern swig_intgo _wrap_a_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_b_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_c_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_x_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_y_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_z_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_side_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_black_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_left_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_right_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_a_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_b_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_c_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_x_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_y_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_z_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_side_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_any_button_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_extra_buttons_show_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_extra_buttons_hide_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_extra_buttons_visible_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_set_extra_buttons_visible_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_point2_x_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_point2_x_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_point2_y_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_point2_y_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern uintptr_t _wrap_new_point2_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_delete_point2_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_point3_x_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_point3_x_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_point3_y_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_point3_y_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_point3_z_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_point3_z_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern uintptr_t _wrap_new_point3_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_delete_point3_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_rectangle_ulx_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_rectangle_ulx_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_rectangle_uly_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_rectangle_uly_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_rectangle_width_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_rectangle_width_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_rectangle_height_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_rectangle_height_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern uintptr_t _wrap_new_rectangle_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_delete_rectangle_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern uintptr_t _wrap_create_point2_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern uintptr_t _wrap_create_point3_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern uintptr_t _wrap_create_rectangle_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4);
extern void _wrap_pixel_r_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_pixel_r_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_pixel_g_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_pixel_g_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_pixel_b_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_pixel_b_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern uintptr_t _wrap_new_pixel_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_delete_pixel_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern swig_intgo _wrap_LOW_RES_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_MED_RES_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_HIGH_RES_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_NATIVE_RES_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_WHITE_2016_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_BLACK_2017_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_camera_open_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_camera_open_black_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_camera_open_at_res_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_camera_open_device_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_camera_open_device_model_at_res_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern swig_intgo _wrap_camera_load_config_wallaby_78ff119e04ce6c7b(swig_type_7 arg1);
extern void _wrap_set_camera_width_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_set_camera_height_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_get_camera_width_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_camera_height_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_camera_update_wallaby_78ff119e04ce6c7b(void);
extern uintptr_t _wrap_get_camera_pixel_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern swig_intgo _wrap_get_channel_count_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_object_count_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_type_8 _wrap_get_object_data_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_code_num_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_data_length_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern double _wrap_get_object_confidence_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_area_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern uintptr_t _wrap_get_object_bbox_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_bbox_ulx_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_bbox_uly_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_bbox_brx_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_bbox_bry_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_bbox_width_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_bbox_height_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern uintptr_t _wrap_get_object_centroid_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_centroid_column_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_centroid_x_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_centroid_row_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_centroid_y_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern uintptr_t _wrap_get_object_center_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_center_column_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_center_x_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_center_row_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_object_center_y_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_camera_close_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_set_camera_config_base_path_wallaby_78ff119e04ce6c7b(swig_type_9 arg1);
extern swig_voidp _wrap_get_camera_frame_row_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_voidp _wrap_get_camera_frame_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_camera_element_size_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_calibrate_compass_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_set_compass_params_wallaby_78ff119e04ce6c7b(float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7);
extern float _wrap_get_compass_angle_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_console_clear_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_create_connect_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_create_connect_once_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_create_disconnect_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_create_start_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_create_passive_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_create_safe_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_create_full_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_create_spot_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_create_cover_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_create_demo_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_create_cover_dock_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_mode_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_lbump_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rbump_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_lwdrop_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_cwdrop_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rwdrop_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_wall_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_lcliff_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_lfcliff_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rfcliff_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rcliff_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_llightbump_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_lflightbump_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_lclightbump_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rclightbump_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rflightbump_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rlightbump_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_llightbump_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rlightbump_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_lflightbump_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_lclightbump_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rclightbump_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rflightbump_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_vwall_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_overcurrents_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_infrared_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_advance_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_play_button_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_normalized_angle_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_set_create_normalized_angle_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_get_create_total_angle_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_set_create_total_angle_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_get_create_distance_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_set_create_distance_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_get_create_battery_charging_state_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_battery_voltage_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_battery_current_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_battery_temp_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_battery_charge_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_battery_capacity_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_wall_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_lcliff_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_lfcliff_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rfcliff_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_rcliff_amt_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_bay_DI_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_bay_AI_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_song_number_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_song_playing_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_number_of_stream_packets_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_requested_velocity_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_requested_radius_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_requested_right_velocity_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_requested_left_velocity_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_create_stop_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_create_drive_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_create_drive_straight_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_create_spin_CW_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_create_spin_CCW_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_create_drive_direct_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_create_spin_block_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap__create_get_raw_encoders_wallaby_78ff119e04ce6c7b(swig_voidp arg1, swig_voidp arg2);
extern void _wrap_create_advance_led_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_create_play_led_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_create_power_led_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_create_digital_output_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_create_pwm_low_side_drivers_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern void _wrap_create_low_side_drivers_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern void _wrap_create_load_song_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_create_play_song_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_create_read_block_wallaby_78ff119e04ce6c7b(swig_type_10 arg1, swig_intgo arg2);
extern void _wrap_create_write_byte_wallaby_78ff119e04ce6c7b(char arg1);
extern void _wrap_create_clear_serial_buffer_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_Baud57600_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_Baud115200_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_create_baud_rate_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_set_create_baud_rate_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_digital_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_set_digital_value_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_digital_value_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_set_digital_output_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_digital_output_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_get_digital_pullup_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_set_digital_pullup_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_display_clear_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_display_printf_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2, swig_type_11 arg3);
extern void _wrap_set_auto_publish_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_publish_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_halt_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_freeze_halt_wallaby_78ff119e04ce6c7b(void);
extern short _wrap_gyro_x_wallaby_78ff119e04ce6c7b(void);
extern short _wrap_gyro_y_wallaby_78ff119e04ce6c7b(void);
extern short _wrap_gyro_z_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_gyro_calibrate_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_ir_read_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_ir_write_wallaby_78ff119e04ce6c7b(void);
extern short _wrap_magneto_x_wallaby_78ff119e04ce6c7b(void);
extern short _wrap_magneto_y_wallaby_78ff119e04ce6c7b(void);
extern short _wrap_magneto_z_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_magneto_calibrate_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_get_motor_position_counter_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_gmpc_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_clear_motor_position_counter_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_cmpc_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_move_at_velocity_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_mav_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_move_to_position_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern swig_intgo _wrap_mtp_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern swig_intgo _wrap_move_relative_position_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern swig_intgo _wrap_mrp_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern void _wrap_set_pid_gains_wallaby_78ff119e04ce6c7b(swig_intgo arg1, short arg2, short arg3, short arg4, short arg5, short arg6, short arg7);
extern void _wrap_get_pid_gains_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_voidp arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5, swig_voidp arg6, swig_voidp arg7);
extern swig_intgo _wrap_freeze_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_get_motor_done_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_block_motor_done_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_bmd_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_setpwm_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_getpwm_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_fd_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_bk_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_motor_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_motor_power_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_off_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_alloff_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_ao_wallaby_78ff119e04ce6c7b(void);
extern swig_type_12 _wrap_get_robot_states_sequence_num_wallaby_78ff119e04ce6c7b(void);
extern swig_type_13 _wrap_get_robot_update_count_wallaby_78ff119e04ce6c7b(void);
extern short _wrap_get_robot_firmware_version_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_set_robot_update_delay_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_get_robot_update_delay_wallaby_78ff119e04ce6c7b(void);
extern swig_intgo _wrap_set_low_volt_threshold_wallaby_78ff119e04ce6c7b(float arg1);
extern float _wrap_get_low_volt_threshold_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_enable_servo_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_disable_servo_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_enable_servos_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_disable_servos_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_set_servo_enabled_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern swig_intgo _wrap_get_servo_enabled_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern swig_intgo _wrap_get_servo_position_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_set_servo_position_wallaby_78ff119e04ce6c7b(swig_intgo arg1, swig_intgo arg2);
extern void _wrap_mutex_data_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_mutex_data_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern uintptr_t _wrap_new_mutex_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_delete_mutex_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_thread_data_set_wallaby_78ff119e04ce6c7b(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_thread_data_get_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern uintptr_t _wrap_new_thread_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_delete_thread_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern uintptr_t _wrap_mutex_create_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_mutex_lock_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern swig_intgo _wrap_mutex_trylock_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_mutex_unlock_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_mutex_destroy_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern uintptr_t _wrap_thread_create_wallaby_78ff119e04ce6c7b(swig_voidp arg1);
extern void _wrap_thread_start_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_thread_wait_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_thread_destroy_wallaby_78ff119e04ce6c7b(uintptr_t arg1);
extern void _wrap_msleep_wallaby_78ff119e04ce6c7b(swig_type_14 arg1);
extern swig_type_15 _wrap_systime_wallaby_78ff119e04ce6c7b(void);
extern double _wrap_seconds_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_milliseconds_wallaby_78ff119e04ce6c7b(swig_type_16 arg1);
extern void _wrap_wait_for_touch_wallaby_78ff119e04ce6c7b(swig_intgo arg1);
extern void _wrap_wait_for_a_button_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_b_button_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_c_button_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_x_button_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_y_button_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_z_button_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_side_button_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_any_button_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_a_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_b_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_c_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_x_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_y_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_z_button_clicked_wallaby_78ff119e04ce6c7b(void);
extern void _wrap_wait_for_side_button_clicked_wallaby_78ff119e04ce6c7b(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Accel_x() (_swig_ret int16) {
	var swig_r int16
	swig_r = (int16)(C._wrap_accel_x_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Accel_y() (_swig_ret int16) {
	var swig_r int16
	swig_r = (int16)(C._wrap_accel_y_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Accel_z() (_swig_ret int16) {
	var swig_r int16
	swig_r = (int16)(C._wrap_accel_z_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Accel_calibrate() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_accel_calibrate_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Analog(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_analog_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Analog8(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_analog8_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Analog10(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_analog10_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Analog12(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_analog12_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Analog_et(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_analog_et_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Set_analog_pullup(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_set_analog_pullup_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Get_analog_pullup(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_get_analog_pullup_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Beep() {
	C._wrap_beep_wallaby_78ff119e04ce6c7b()
}

func Battery_charging() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_battery_charging_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Power_level() (_swig_ret float32) {
	var swig_r float32
	swig_r = (float32)(C._wrap_power_level_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Power_level_nimh() (_swig_ret float32) {
	var swig_r float32
	swig_r = (float32)(C._wrap_power_level_nimh_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Power_level_lipo() (_swig_ret float32) {
	var swig_r float32
	swig_r = (float32)(C._wrap_power_level_lipo_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Power_level_life() (_swig_ret float32) {
	var swig_r float32
	swig_r = (float32)(C._wrap_power_level_life_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Shut_down_in(arg1 float64) {
	_swig_i_0 := arg1
	C._wrap_shut_down_in_wallaby_78ff119e04ce6c7b(C.double(_swig_i_0))
}

func Wait_for_light(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_wait_for_light_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Set_a_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_a_button_text_wallaby_78ff119e04ce6c7b(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_b_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_b_button_text_wallaby_78ff119e04ce6c7b(*(*C.swig_type_2)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_c_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_c_button_text_wallaby_78ff119e04ce6c7b(*(*C.swig_type_3)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_x_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_x_button_text_wallaby_78ff119e04ce6c7b(*(*C.swig_type_4)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_y_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_y_button_text_wallaby_78ff119e04ce6c7b(*(*C.swig_type_5)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_z_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_z_button_text_wallaby_78ff119e04ce6c7b(*(*C.swig_type_6)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func A_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_a_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func B_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_b_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func C_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_c_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func X_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_x_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Y_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_y_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Z_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_z_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Side_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_side_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Black_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_black_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Left_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_left_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Right_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_right_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func A_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_a_button_clicked_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func B_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_b_button_clicked_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func C_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_c_button_clicked_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func X_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_x_button_clicked_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Y_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_y_button_clicked_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Z_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_z_button_clicked_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Side_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_side_button_clicked_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Any_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_any_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Extra_buttons_show() {
	C._wrap_extra_buttons_show_wallaby_78ff119e04ce6c7b()
}

func Extra_buttons_hide() {
	C._wrap_extra_buttons_hide_wallaby_78ff119e04ce6c7b()
}

func Get_extra_buttons_visible() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_extra_buttons_visible_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Set_extra_buttons_visible(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_set_extra_buttons_visible_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

type SwigcptrPoint2 uintptr

func (p SwigcptrPoint2) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrPoint2) SwigIsPoint2() {
}

func (arg1 SwigcptrPoint2) SetX(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_point2_x_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrPoint2) GetX() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_point2_x_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrPoint2) SetY(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_point2_y_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrPoint2) GetY() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_point2_y_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewPoint2() (_swig_ret Point2) {
	var swig_r Point2
	swig_r = (Point2)(SwigcptrPoint2(C._wrap_new_point2_wallaby_78ff119e04ce6c7b()))
	return swig_r
}

func DeletePoint2(arg1 Point2) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_point2_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

type Point2 interface {
	Swigcptr() uintptr
	SwigIsPoint2()
	SetX(arg2 int)
	GetX() (_swig_ret int)
	SetY(arg2 int)
	GetY() (_swig_ret int)
}

type SwigcptrPoint3 uintptr

func (p SwigcptrPoint3) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrPoint3) SwigIsPoint3() {
}

func (arg1 SwigcptrPoint3) SetX(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_point3_x_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrPoint3) GetX() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_point3_x_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrPoint3) SetY(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_point3_y_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrPoint3) GetY() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_point3_y_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrPoint3) SetZ(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_point3_z_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrPoint3) GetZ() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_point3_z_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewPoint3() (_swig_ret Point3) {
	var swig_r Point3
	swig_r = (Point3)(SwigcptrPoint3(C._wrap_new_point3_wallaby_78ff119e04ce6c7b()))
	return swig_r
}

func DeletePoint3(arg1 Point3) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_point3_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

type Point3 interface {
	Swigcptr() uintptr
	SwigIsPoint3()
	SetX(arg2 int)
	GetX() (_swig_ret int)
	SetY(arg2 int)
	GetY() (_swig_ret int)
	SetZ(arg2 int)
	GetZ() (_swig_ret int)
}

type SwigcptrRectangle uintptr

func (p SwigcptrRectangle) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrRectangle) SwigIsRectangle() {
}

func (arg1 SwigcptrRectangle) SetUlx(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_rectangle_ulx_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrRectangle) GetUlx() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_rectangle_ulx_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) SetUly(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_rectangle_uly_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrRectangle) GetUly() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_rectangle_uly_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) SetWidth(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_rectangle_width_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrRectangle) GetWidth() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_rectangle_width_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) SetHeight(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_rectangle_height_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrRectangle) GetHeight() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_rectangle_height_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewRectangle() (_swig_ret Rectangle) {
	var swig_r Rectangle
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_new_rectangle_wallaby_78ff119e04ce6c7b()))
	return swig_r
}

func DeleteRectangle(arg1 Rectangle) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_rectangle_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

type Rectangle interface {
	Swigcptr() uintptr
	SwigIsRectangle()
	SetUlx(arg2 int)
	GetUlx() (_swig_ret int)
	SetUly(arg2 int)
	GetUly() (_swig_ret int)
	SetWidth(arg2 int)
	GetWidth() (_swig_ret int)
	SetHeight(arg2 int)
	GetHeight() (_swig_ret int)
}

func Create_point2(arg1 int, arg2 int) (_swig_ret Point2) {
	var swig_r Point2
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Point2)(SwigcptrPoint2(C._wrap_create_point2_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func Create_point3(arg1 int, arg2 int, arg3 int) (_swig_ret Point3) {
	var swig_r Point3
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Point3)(SwigcptrPoint3(C._wrap_create_point3_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))))
	return swig_r
}

func Create_rectangle(arg1 int, arg2 int, arg3 int, arg4 int) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_create_rectangle_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3))))
	return swig_r
}

type SwigcptrPixel uintptr

func (p SwigcptrPixel) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrPixel) SwigIsPixel() {
}

func (arg1 SwigcptrPixel) SetR(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_pixel_r_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrPixel) GetR() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_pixel_r_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrPixel) SetG(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_pixel_g_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrPixel) GetG() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_pixel_g_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrPixel) SetB(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_pixel_b_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrPixel) GetB() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_pixel_b_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewPixel() (_swig_ret Pixel) {
	var swig_r Pixel
	swig_r = (Pixel)(SwigcptrPixel(C._wrap_new_pixel_wallaby_78ff119e04ce6c7b()))
	return swig_r
}

func DeletePixel(arg1 Pixel) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_pixel_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

type Pixel interface {
	Swigcptr() uintptr
	SwigIsPixel()
	SetR(arg2 int)
	GetR() (_swig_ret int)
	SetG(arg2 int)
	GetG() (_swig_ret int)
	SetB(arg2 int)
	GetB() (_swig_ret int)
}

type Enum_SS_Resolution int
func _swig_getLOW_RES() (_swig_ret Enum_SS_Resolution) {
	var swig_r Enum_SS_Resolution
	swig_r = (Enum_SS_Resolution)(C._wrap_LOW_RES_wallaby_78ff119e04ce6c7b())
	return swig_r
}

var LOW_RES Enum_SS_Resolution = _swig_getLOW_RES()
func _swig_getMED_RES() (_swig_ret Enum_SS_Resolution) {
	var swig_r Enum_SS_Resolution
	swig_r = (Enum_SS_Resolution)(C._wrap_MED_RES_wallaby_78ff119e04ce6c7b())
	return swig_r
}

var MED_RES Enum_SS_Resolution = _swig_getMED_RES()
func _swig_getHIGH_RES() (_swig_ret Enum_SS_Resolution) {
	var swig_r Enum_SS_Resolution
	swig_r = (Enum_SS_Resolution)(C._wrap_HIGH_RES_wallaby_78ff119e04ce6c7b())
	return swig_r
}

var HIGH_RES Enum_SS_Resolution = _swig_getHIGH_RES()
func _swig_getNATIVE_RES() (_swig_ret Enum_SS_Resolution) {
	var swig_r Enum_SS_Resolution
	swig_r = (Enum_SS_Resolution)(C._wrap_NATIVE_RES_wallaby_78ff119e04ce6c7b())
	return swig_r
}

var NATIVE_RES Enum_SS_Resolution = _swig_getNATIVE_RES()
type Enum_SS_Model int
func _swig_getWHITE_2016() (_swig_ret Enum_SS_Model) {
	var swig_r Enum_SS_Model
	swig_r = (Enum_SS_Model)(C._wrap_WHITE_2016_wallaby_78ff119e04ce6c7b())
	return swig_r
}

var WHITE_2016 Enum_SS_Model = _swig_getWHITE_2016()
func _swig_getBLACK_2017() (_swig_ret Enum_SS_Model) {
	var swig_r Enum_SS_Model
	swig_r = (Enum_SS_Model)(C._wrap_BLACK_2017_wallaby_78ff119e04ce6c7b())
	return swig_r
}

var BLACK_2017 Enum_SS_Model = _swig_getBLACK_2017()
func Camera_open() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_camera_open_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Camera_open_black() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_camera_open_black_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Camera_open_at_res(arg1 Enum_SS_Resolution) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_camera_open_at_res_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Camera_open_device(arg1 int, arg2 Enum_SS_Resolution) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_camera_open_device_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Camera_open_device_model_at_res(arg1 int, arg2 Enum_SS_Model, arg3 Enum_SS_Resolution) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_camera_open_device_model_at_res_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Camera_load_config(arg1 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_camera_load_config_wallaby_78ff119e04ce6c7b(*(*C.swig_type_7)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Set_camera_width(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_set_camera_width_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Set_camera_height(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_set_camera_height_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Get_camera_width() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_camera_width_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_camera_height() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_camera_height_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Camera_update() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_camera_update_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_camera_pixel(arg1 Point2) (_swig_ret Pixel) {
	var swig_r Pixel
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Pixel)(SwigcptrPixel(C._wrap_get_camera_pixel_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Get_channel_count() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_channel_count_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_object_count(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_get_object_count_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Get_object_data(arg1 int, arg2 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_get_object_data_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func Get_code_num(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_code_num_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_data_length(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_data_length_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_confidence(arg1 int, arg2 int) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (float64)(C._wrap_get_object_confidence_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_area(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_area_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_bbox(arg1 int, arg2 int) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_get_object_bbox_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func Get_object_bbox_ulx(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_bbox_ulx_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_bbox_uly(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_bbox_uly_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_bbox_brx(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_bbox_brx_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_bbox_bry(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_bbox_bry_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_bbox_width(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_bbox_width_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_bbox_height(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_bbox_height_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_centroid(arg1 int, arg2 int) (_swig_ret Point2) {
	var swig_r Point2
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Point2)(SwigcptrPoint2(C._wrap_get_object_centroid_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func Get_object_centroid_column(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_centroid_column_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_centroid_x(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_centroid_x_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_centroid_row(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_centroid_row_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_centroid_y(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_centroid_y_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_center(arg1 int, arg2 int) (_swig_ret Point2) {
	var swig_r Point2
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Point2)(SwigcptrPoint2(C._wrap_get_object_center_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func Get_object_center_column(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_center_column_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_center_x(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_center_x_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_center_row(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_center_row_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Get_object_center_y(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_get_object_center_y_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Camera_close() {
	C._wrap_camera_close_wallaby_78ff119e04ce6c7b()
}

func Set_camera_config_base_path(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_camera_config_base_path_wallaby_78ff119e04ce6c7b(*(*C.swig_type_9)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Get_camera_frame_row(arg1 uint) (_swig_ret *byte) {
	var swig_r *byte
	_swig_i_0 := arg1
	swig_r = (*byte)(C._wrap_get_camera_frame_row_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Get_camera_frame() (_swig_ret *byte) {
	var swig_r *byte
	swig_r = (*byte)(C._wrap_get_camera_frame_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_camera_element_size() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_get_camera_element_size_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Calibrate_compass() {
	C._wrap_calibrate_compass_wallaby_78ff119e04ce6c7b()
}

func Set_compass_params(arg1 float32, arg2 float32, arg3 float32, arg4 float32, arg5 float32, arg6 float32, arg7 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	C._wrap_set_compass_params_wallaby_78ff119e04ce6c7b(C.float(_swig_i_0), C.float(_swig_i_1), C.float(_swig_i_2), C.float(_swig_i_3), C.float(_swig_i_4), C.float(_swig_i_5), C.float(_swig_i_6))
}

func Get_compass_angle() (_swig_ret float32) {
	var swig_r float32
	swig_r = (float32)(C._wrap_get_compass_angle_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Console_clear() {
	C._wrap_console_clear_wallaby_78ff119e04ce6c7b()
}

func Create_connect() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_create_connect_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Create_connect_once() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_create_connect_once_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Create_disconnect() {
	C._wrap_create_disconnect_wallaby_78ff119e04ce6c7b()
}

func Create_start() {
	C._wrap_create_start_wallaby_78ff119e04ce6c7b()
}

func Create_passive() {
	C._wrap_create_passive_wallaby_78ff119e04ce6c7b()
}

func Create_safe() {
	C._wrap_create_safe_wallaby_78ff119e04ce6c7b()
}

func Create_full() {
	C._wrap_create_full_wallaby_78ff119e04ce6c7b()
}

func Create_spot() {
	C._wrap_create_spot_wallaby_78ff119e04ce6c7b()
}

func Create_cover() {
	C._wrap_create_cover_wallaby_78ff119e04ce6c7b()
}

func Create_demo(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_create_demo_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Create_cover_dock() {
	C._wrap_create_cover_dock_wallaby_78ff119e04ce6c7b()
}

func Get_create_mode() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_mode_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_lbump() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_lbump_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rbump() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rbump_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_lwdrop() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_lwdrop_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_cwdrop() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_cwdrop_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rwdrop() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rwdrop_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_wall() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_wall_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_lcliff() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_lcliff_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_lfcliff() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_lfcliff_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rfcliff() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rfcliff_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rcliff() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rcliff_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_llightbump() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_llightbump_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_lflightbump() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_lflightbump_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_lclightbump() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_lclightbump_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rclightbump() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rclightbump_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rflightbump() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rflightbump_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rlightbump() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rlightbump_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_llightbump_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_llightbump_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rlightbump_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rlightbump_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_lflightbump_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_lflightbump_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_lclightbump_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_lclightbump_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rclightbump_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rclightbump_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rflightbump_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rflightbump_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_vwall() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_vwall_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_overcurrents() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_overcurrents_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_infrared() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_infrared_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_advance_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_advance_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_play_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_play_button_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_normalized_angle() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_normalized_angle_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Set_create_normalized_angle(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_set_create_normalized_angle_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Get_create_total_angle() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_total_angle_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Set_create_total_angle(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_set_create_total_angle_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Get_create_distance() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_distance_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Set_create_distance(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_set_create_distance_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Get_create_battery_charging_state() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_battery_charging_state_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_battery_voltage() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_battery_voltage_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_battery_current() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_battery_current_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_battery_temp() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_battery_temp_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_battery_charge() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_battery_charge_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_battery_capacity() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_battery_capacity_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_wall_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_wall_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_lcliff_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_lcliff_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_lfcliff_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_lfcliff_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rfcliff_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rfcliff_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_rcliff_amt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_rcliff_amt_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_bay_DI() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_bay_DI_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_bay_AI() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_bay_AI_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_song_number() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_song_number_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_song_playing() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_song_playing_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_number_of_stream_packets() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_number_of_stream_packets_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_requested_velocity() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_requested_velocity_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_requested_radius() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_requested_radius_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_requested_right_velocity() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_requested_right_velocity_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_create_requested_left_velocity() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_create_requested_left_velocity_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Create_stop() {
	C._wrap_create_stop_wallaby_78ff119e04ce6c7b()
}

func Create_drive(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_create_drive_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Create_drive_straight(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_create_drive_straight_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Create_spin_CW(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_create_spin_CW_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Create_spin_CCW(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_create_spin_CCW_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Create_drive_direct(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_create_drive_direct_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Create_spin_block(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_create_spin_block_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func X_create_get_raw_encoders(arg1 *int64, arg2 *int64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap__create_get_raw_encoders_wallaby_78ff119e04ce6c7b(C.swig_voidp(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func Create_advance_led(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_create_advance_led_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Create_play_led(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_create_play_led_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Create_power_led(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_create_power_led_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Create_digital_output(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_create_digital_output_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Create_pwm_low_side_drivers(arg1 int, arg2 int, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_create_pwm_low_side_drivers_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func Create_low_side_drivers(arg1 int, arg2 int, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_create_low_side_drivers_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func Create_load_song(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_create_load_song_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Create_play_song(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_create_play_song_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Create_read_block(arg1 string, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_create_read_block_wallaby_78ff119e04ce6c7b(*(*C.swig_type_10)(unsafe.Pointer(&_swig_i_0)), C.swig_intgo(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Create_write_byte(arg1 byte) {
	_swig_i_0 := arg1
	C._wrap_create_write_byte_wallaby_78ff119e04ce6c7b(C.char(_swig_i_0))
}

func Create_clear_serial_buffer() {
	C._wrap_create_clear_serial_buffer_wallaby_78ff119e04ce6c7b()
}

type Enum_SS_BaudRate int
func _swig_getBaud57600() (_swig_ret Enum_SS_BaudRate) {
	var swig_r Enum_SS_BaudRate
	swig_r = (Enum_SS_BaudRate)(C._wrap_Baud57600_wallaby_78ff119e04ce6c7b())
	return swig_r
}

var Baud57600 Enum_SS_BaudRate = _swig_getBaud57600()
func _swig_getBaud115200() (_swig_ret Enum_SS_BaudRate) {
	var swig_r Enum_SS_BaudRate
	swig_r = (Enum_SS_BaudRate)(C._wrap_Baud115200_wallaby_78ff119e04ce6c7b())
	return swig_r
}

var Baud115200 Enum_SS_BaudRate = _swig_getBaud115200()
func Get_create_baud_rate() (_swig_ret Enum_SS_BaudRate) {
	var swig_r Enum_SS_BaudRate
	swig_r = (Enum_SS_BaudRate)(C._wrap_get_create_baud_rate_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Set_create_baud_rate(arg1 Enum_SS_BaudRate) {
	_swig_i_0 := arg1
	C._wrap_set_create_baud_rate_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Digital(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_digital_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Set_digital_value(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_set_digital_value_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Get_digital_value(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_get_digital_value_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Set_digital_output(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_set_digital_output_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Get_digital_output(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_get_digital_output_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Get_digital_pullup(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_get_digital_pullup_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Set_digital_pullup(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_set_digital_pullup_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Display_clear() {
	C._wrap_display_clear_wallaby_78ff119e04ce6c7b()
}

func Display_printf(arg1 int, arg2 int, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_display_printf_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func Set_auto_publish(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_set_auto_publish_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Publish() {
	C._wrap_publish_wallaby_78ff119e04ce6c7b()
}

func Halt() {
	C._wrap_halt_wallaby_78ff119e04ce6c7b()
}

func Freeze_halt() {
	C._wrap_freeze_halt_wallaby_78ff119e04ce6c7b()
}

func Gyro_x() (_swig_ret int16) {
	var swig_r int16
	swig_r = (int16)(C._wrap_gyro_x_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Gyro_y() (_swig_ret int16) {
	var swig_r int16
	swig_r = (int16)(C._wrap_gyro_y_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Gyro_z() (_swig_ret int16) {
	var swig_r int16
	swig_r = (int16)(C._wrap_gyro_z_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Gyro_calibrate() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_gyro_calibrate_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Ir_read() {
	C._wrap_ir_read_wallaby_78ff119e04ce6c7b()
}

func Ir_write() {
	C._wrap_ir_write_wallaby_78ff119e04ce6c7b()
}

func Magneto_x() (_swig_ret int16) {
	var swig_r int16
	swig_r = (int16)(C._wrap_magneto_x_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Magneto_y() (_swig_ret int16) {
	var swig_r int16
	swig_r = (int16)(C._wrap_magneto_y_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Magneto_z() (_swig_ret int16) {
	var swig_r int16
	swig_r = (int16)(C._wrap_magneto_z_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Magneto_calibrate() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_magneto_calibrate_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_motor_position_counter(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_get_motor_position_counter_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Gmpc(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_gmpc_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Clear_motor_position_counter(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_clear_motor_position_counter_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Cmpc(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_cmpc_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Move_at_velocity(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_move_at_velocity_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Mav(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_mav_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Move_to_position(arg1 int, arg2 int, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_move_to_position_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Mtp(arg1 int, arg2 int, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_mtp_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Move_relative_position(arg1 int, arg2 int, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_move_relative_position_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Mrp(arg1 int, arg2 int, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_mrp_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func Set_pid_gains(arg1 int, arg2 int16, arg3 int16, arg4 int16, arg5 int16, arg6 int16, arg7 int16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	C._wrap_set_pid_gains_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.short(_swig_i_3), C.short(_swig_i_4), C.short(_swig_i_5), C.short(_swig_i_6))
}

func Get_pid_gains(arg1 int, arg2 *int16, arg3 *int16, arg4 *int16, arg5 *int16, arg6 *int16, arg7 *int16) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	C._wrap_get_pid_gains_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6))
}

func Freeze(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_freeze_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Get_motor_done(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_get_motor_done_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Block_motor_done(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_block_motor_done_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Bmd(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_bmd_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Setpwm(arg1 int, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_setpwm_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func Getpwm(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_getpwm_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Fd(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_fd_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Bk(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_bk_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Motor(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_motor_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Motor_power(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_motor_power_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Off(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_off_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Alloff() {
	C._wrap_alloff_wallaby_78ff119e04ce6c7b()
}

func Ao() {
	C._wrap_ao_wallaby_78ff119e04ce6c7b()
}

func Get_robot_states_sequence_num() (_swig_ret uint64) {
	var swig_r uint64
	swig_r = (uint64)(C._wrap_get_robot_states_sequence_num_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_robot_update_count() (_swig_ret uint64) {
	var swig_r uint64
	swig_r = (uint64)(C._wrap_get_robot_update_count_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Get_robot_firmware_version() (_swig_ret uint16) {
	var swig_r uint16
	swig_r = (uint16)(C._wrap_get_robot_firmware_version_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Set_robot_update_delay(arg1 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_set_robot_update_delay_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Get_robot_update_delay() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_get_robot_update_delay_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Set_low_volt_threshold(arg1 float32) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_set_low_volt_threshold_wallaby_78ff119e04ce6c7b(C.float(_swig_i_0)))
	return swig_r
}

func Get_low_volt_threshold() (_swig_ret float32) {
	var swig_r float32
	swig_r = (float32)(C._wrap_get_low_volt_threshold_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Enable_servo(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_enable_servo_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Disable_servo(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_disable_servo_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Enable_servos() {
	C._wrap_enable_servos_wallaby_78ff119e04ce6c7b()
}

func Disable_servos() {
	C._wrap_disable_servos_wallaby_78ff119e04ce6c7b()
}

func Set_servo_enabled(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_set_servo_enabled_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func Get_servo_enabled(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_get_servo_enabled_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Get_servo_position(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_get_servo_position_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Set_servo_position(arg1 int, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_set_servo_position_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1))
}

type SwigcptrMutex uintptr

func (p SwigcptrMutex) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrMutex) SwigIsMutex() {
}

func (arg1 SwigcptrMutex) SetData(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_mutex_data_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrMutex) GetData() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_mutex_data_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewMutex() (_swig_ret Mutex) {
	var swig_r Mutex
	swig_r = (Mutex)(SwigcptrMutex(C._wrap_new_mutex_wallaby_78ff119e04ce6c7b()))
	return swig_r
}

func DeleteMutex(arg1 Mutex) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_mutex_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

type Mutex interface {
	Swigcptr() uintptr
	SwigIsMutex()
	SetData(arg2 uintptr)
	GetData() (_swig_ret uintptr)
}

type SwigcptrThread uintptr

func (p SwigcptrThread) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrThread) SwigIsThread() {
}

func (arg1 SwigcptrThread) SetData(arg2 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_thread_data_set_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrThread) GetData() (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_thread_data_get_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewThread() (_swig_ret Thread) {
	var swig_r Thread
	swig_r = (Thread)(SwigcptrThread(C._wrap_new_thread_wallaby_78ff119e04ce6c7b()))
	return swig_r
}

func DeleteThread(arg1 Thread) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_thread_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

type Thread interface {
	Swigcptr() uintptr
	SwigIsThread()
	SetData(arg2 uintptr)
	GetData() (_swig_ret uintptr)
}

func Mutex_create() (_swig_ret Mutex) {
	var swig_r Mutex
	swig_r = (Mutex)(SwigcptrMutex(C._wrap_mutex_create_wallaby_78ff119e04ce6c7b()))
	return swig_r
}

func Mutex_lock(arg1 Mutex) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_mutex_lock_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

func Mutex_trylock(arg1 Mutex) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_mutex_trylock_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Mutex_unlock(arg1 Mutex) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_mutex_unlock_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

func Mutex_destroy(arg1 Mutex) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_mutex_destroy_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

func Thread_create(arg1 *_swig_fnptr) (_swig_ret Thread) {
	var swig_r Thread
	_swig_i_0 := arg1
	swig_r = (Thread)(SwigcptrThread(C._wrap_thread_create_wallaby_78ff119e04ce6c7b(C.swig_voidp(_swig_i_0))))
	return swig_r
}

func Thread_start(arg1 Thread) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_thread_start_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

func Thread_wait(arg1 Thread) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_thread_wait_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

func Thread_destroy(arg1 Thread) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_thread_destroy_wallaby_78ff119e04ce6c7b(C.uintptr_t(_swig_i_0))
}

func Msleep(arg1 int64) {
	_swig_i_0 := arg1
	C._wrap_msleep_wallaby_78ff119e04ce6c7b(C.swig_type_14(_swig_i_0))
}

func Systime() (_swig_ret uint64) {
	var swig_r uint64
	swig_r = (uint64)(C._wrap_systime_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Seconds() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_seconds_wallaby_78ff119e04ce6c7b())
	return swig_r
}

func Wait_for_milliseconds(arg1 int64) {
	_swig_i_0 := arg1
	C._wrap_wait_for_milliseconds_wallaby_78ff119e04ce6c7b(C.swig_type_16(_swig_i_0))
}

func Wait_for_touch(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_wait_for_touch_wallaby_78ff119e04ce6c7b(C.swig_intgo(_swig_i_0))
}

func Wait_for_a_button() {
	C._wrap_wait_for_a_button_wallaby_78ff119e04ce6c7b()
}

func Wait_for_b_button() {
	C._wrap_wait_for_b_button_wallaby_78ff119e04ce6c7b()
}

func Wait_for_c_button() {
	C._wrap_wait_for_c_button_wallaby_78ff119e04ce6c7b()
}

func Wait_for_x_button() {
	C._wrap_wait_for_x_button_wallaby_78ff119e04ce6c7b()
}

func Wait_for_y_button() {
	C._wrap_wait_for_y_button_wallaby_78ff119e04ce6c7b()
}

func Wait_for_z_button() {
	C._wrap_wait_for_z_button_wallaby_78ff119e04ce6c7b()
}

func Wait_for_side_button() {
	C._wrap_wait_for_side_button_wallaby_78ff119e04ce6c7b()
}

func Wait_for_any_button() {
	C._wrap_wait_for_any_button_wallaby_78ff119e04ce6c7b()
}

func Wait_for_a_button_clicked() {
	C._wrap_wait_for_a_button_clicked_wallaby_78ff119e04ce6c7b()
}

func Wait_for_b_button_clicked() {
	C._wrap_wait_for_b_button_clicked_wallaby_78ff119e04ce6c7b()
}

func Wait_for_c_button_clicked() {
	C._wrap_wait_for_c_button_clicked_wallaby_78ff119e04ce6c7b()
}

func Wait_for_x_button_clicked() {
	C._wrap_wait_for_x_button_clicked_wallaby_78ff119e04ce6c7b()
}

func Wait_for_y_button_clicked() {
	C._wrap_wait_for_y_button_clicked_wallaby_78ff119e04ce6c7b()
}

func Wait_for_z_button_clicked() {
	C._wrap_wait_for_z_button_clicked_wallaby_78ff119e04ce6c7b()
}

func Wait_for_side_button_clicked() {
	C._wrap_wait_for_side_button_clicked_wallaby_78ff119e04ce6c7b()
}


