/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: wbutton.i

package wbutton

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef int intgo;
typedef unsigned int uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
extern void _wrap_Swig_free_wbutton_dbdebf929f8e45cf(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_wbutton_dbdebf929f8e45cf(swig_intgo arg1);
extern void _wrap_set_a_button_text_wbutton_dbdebf929f8e45cf(swig_type_1 arg1);
extern void _wrap_set_b_button_text_wbutton_dbdebf929f8e45cf(swig_type_2 arg1);
extern void _wrap_set_c_button_text_wbutton_dbdebf929f8e45cf(swig_type_3 arg1);
extern void _wrap_set_x_button_text_wbutton_dbdebf929f8e45cf(swig_type_4 arg1);
extern void _wrap_set_y_button_text_wbutton_dbdebf929f8e45cf(swig_type_5 arg1);
extern void _wrap_set_z_button_text_wbutton_dbdebf929f8e45cf(swig_type_6 arg1);
extern swig_intgo _wrap_a_button_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_b_button_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_c_button_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_x_button_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_y_button_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_z_button_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_side_button_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_black_button_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_left_button_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_right_button_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_a_button_clicked_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_b_button_clicked_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_c_button_clicked_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_x_button_clicked_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_y_button_clicked_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_z_button_clicked_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_side_button_clicked_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_any_button_wbutton_dbdebf929f8e45cf(void);
extern void _wrap_extra_buttons_show_wbutton_dbdebf929f8e45cf(void);
extern void _wrap_extra_buttons_hide_wbutton_dbdebf929f8e45cf(void);
extern swig_intgo _wrap_get_extra_buttons_visible_wbutton_dbdebf929f8e45cf(void);
extern void _wrap_set_extra_buttons_visible_wbutton_dbdebf929f8e45cf(swig_intgo arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_wbutton_dbdebf929f8e45cf(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_wbutton_dbdebf929f8e45cf(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Set_a_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_a_button_text_wbutton_dbdebf929f8e45cf(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_b_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_b_button_text_wbutton_dbdebf929f8e45cf(*(*C.swig_type_2)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_c_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_c_button_text_wbutton_dbdebf929f8e45cf(*(*C.swig_type_3)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_x_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_x_button_text_wbutton_dbdebf929f8e45cf(*(*C.swig_type_4)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_y_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_y_button_text_wbutton_dbdebf929f8e45cf(*(*C.swig_type_5)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func Set_z_button_text(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_set_z_button_text_wbutton_dbdebf929f8e45cf(*(*C.swig_type_6)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func A_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_a_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func B_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_b_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func C_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_c_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func X_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_x_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Y_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_y_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Z_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_z_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Side_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_side_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Black_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_black_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Left_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_left_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Right_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_right_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func A_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_a_button_clicked_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func B_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_b_button_clicked_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func C_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_c_button_clicked_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func X_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_x_button_clicked_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Y_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_y_button_clicked_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Z_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_z_button_clicked_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Side_button_clicked() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_side_button_clicked_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Any_button() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_any_button_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Extra_buttons_show() {
	C._wrap_extra_buttons_show_wbutton_dbdebf929f8e45cf()
}

func Extra_buttons_hide() {
	C._wrap_extra_buttons_hide_wbutton_dbdebf929f8e45cf()
}

func Get_extra_buttons_visible() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_get_extra_buttons_visible_wbutton_dbdebf929f8e45cf())
	return swig_r
}

func Set_extra_buttons_visible(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_set_extra_buttons_visible_wbutton_dbdebf929f8e45cf(C.swig_intgo(_swig_i_0))
}


